# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

# Set the working directory
WORKDIR /app

COPY ./requirements.txt /app/requirements.txt


RUN apt update 
RUN apt install -y python3-pip
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

EXPOSE 3000
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=3000"]